# All Quotes
# Will return first Quotes 20 by default
# Accepts both limit and skip in query  example {?limit=10&skip=5}
GET http://localhost:8080/Quotes

###
# Single Quote
# Will return one Quote requested by ID
GET http://localhost:8080/Quotes/q/6

###
# Random Quote
# Will return random Quote
GET http://localhost:8080/Quotes/random