# All User
# Will return first Users 20 by default
# Accepts both limit and skip in query  example {?limit=10&skip=5}
GET http://localhost:8080/Users

###
# Single User
# Will return one User requested by ID
GET http://localhost:8080/Users/user/5

###
# Search Users
# Will return first Users 5 by default
# Accepts both limit and skip in query  example {?limit=10&skip=5}
GET http://localhost:8080/Users/search?Search=Emily Smith Johnson


###
# Filter Users
# Can be Single property or could be nested properties seperated by "." in key 
# Will Return filtered Users by provided property or nested property's value
# Accepts Both limit and skip in query example {?limit=2&skip=1} 
GET http://localhost:8080/Users/filter?key=hair.color&value=Red

###
# Sort Users
# Sort by Property must be type of either string or number
# Will sort by the provided property. Also accepts order whether ascending or descending
# By Default sorts in ascending way
# By Default returns first 10
# Accepts both limit and skip in query  example {?limit=10&skip=5}
GET http://localhost:8080/Users/sort?sortby=firstName&order=desc&limit=2&skip=1

###
# Add User
# Some Fields will be added by default for future sorting or other actions
POST  http://localhost:8080/Users/add
Content-Type: application/json

{
	"firstName" : "shaheryar",
	"password" : "fsdfd"

}

###
# Update post
# Must be one of the mentioned default parameters or the parameter that is manually added in add User. And must have same data type
# Must match Data type already provided
# { firstName: "", lastName: "", maidenName: "", age: 18,gender: "", email: "",phone: "",username: "",password: "",birthDate: "",image: "",bloodGroup: "",height: 0,weight: 0,eyeColor: "",hair: {  color: "",  type: ""},ip: "",address: {  address: "",  city: "",  state: "",  stateCode: "",  postalCode: "",  coordinates:    lat: 0,    lng: 0  },  country: ""},macAddress: "",university: "",bank: {  cardExpire: "",  cardNumber: "",  cardType: "",  currency: "",  iban: ""},company: {  department: "",  name: "",  title: "",  address: {    address: "",    city: "",    stateCode: "",    state: "",    postalCode: "",    coordinates: {      lat: 0,      lng: 0    },    country: ""  }},ein: "",ssn: "",userAgent: "",crypto: {  coin: "",  wallet: "",  network: ""},role: ""}
Content-Type: application/json

{
	"firstName" : "Bull Shit"
}

###
# Delete User
DELETE  http://localhost:8080/Users/user/206
